### ISSUE TITLE
关于成立中大gitlab项目组的想法

### ISSUE THREAD

**Issue by huangjj27** [sysu/0sysudotgithubdotcom#2]
尊敬的中大github用户组:
您们好! 我是13届数据学院的一名学生, 最近在筹划成立中大gitlab用户组的事情, 原因如下:

1. 贵组织的项目(尤其是毕业论文模板)基本已经停止, 或由在校学生**各自**开发, 难以凝聚力量使项目持续发展
1. gitlab近年发展迅猛, 而其开放的工作态度, 可控的权限管理也促使我最后选择了它作为项目的集散地

希望能借助贵组织的力量, 为中大莘莘学子提供福利之余, 也为他们提供低风险,高回报的技术训练基地.

[中山大学-gitlab](https://gitlab.com/sysu-gitlab)

**Comment by ltaoist** [comment]
请转移到 https://github.com/sysu/sysu.github.io/issues/1 。
